const API='http://localhost:8000'; let config={services:{},providers:[],today:''};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(msg,bad=false){const t=$('#toast');t.textContent=msg;t.className='toast show '+(bad?'bad':'');setTimeout(()=>t.className='toast',3500)}
async function request(url,opt){const r=await fetch(API+url,opt); if(!r.ok){let x={};try{x=await r.json()}catch{};throw new Error(x.detail||'Request failed')} return r.json()}
function fmt(t){if(!t)return '—';let [h,m]=t.split(':').map(Number);return `${((h+11)%12)+1}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
function badge(a){return `<span class="badge ${a.urgency==='urgent'?'urgent':a.urgency==='priority'?'priority':''}">${a.source==='walk_in'?'WALK-IN':'ONLINE'} · ${a.urgency.toUpperCase()}</span>`}
function actions(a){if(a.status==='completed'||a.status==='cancelled'||a.status==='no_show')return '';
 if(a.status==='in_service')return `<button onclick="setStatus(${a.id},'completed')">Complete</button>`;
 if(a.status==='checked_in'||a.status==='waiting')return `<button onclick="setStatus(${a.id},'in_service')">Start</button>${a.source==='online'?`<button class="ghost" onclick="setStatus(${a.id},'no_show')">No Show</button>`:''}`;
 if(a.status==='scheduled')return `<button onclick="checkIn(${a.id})">Check In</button><button class="ghost" onclick="setStatus(${a.id},'no_show')">No Show</button>`; return ''}
async function loadAll(){await Promise.all([loadQueue(),loadCalendar(),loadNotifications()])}
async function loadQueue(){const p=$('#queueProvider').value||config.providers[0];const [q,a]=await Promise.all([request(`/api/appointments?day=${config.today}&provider=${encodeURIComponent(p)}`),request(`/api/analytics?day=${config.today}`)]);
 $('#stats').innerHTML=`<div><span>Online</span><strong>${a.appointments}</strong></div><div><span>Walk-ins</span><strong>${a.walk_ins}</strong></div><div><span>Waiting</span><strong>${a.waiting}</strong></div><div><span>Completed</span><strong>${a.completed}</strong></div>`;
 const active=q.filter(x=>!['completed','cancelled','no_show'].includes(x.status)); $('#nextEstimate').textContent=active[0]?.predicted_start?fmt(active[0].predicted_start):'No queue';
 $('#queueList').innerHTML=q.length?q.map(a=>`<article class="card ${a.status==='in_service'?'serving':''}"><div class="time"><strong>${a.source==='online'?fmt(a.scheduled_time):'Walk-in'}</strong><small>${a.status.replaceAll('_',' ')}</small></div><div class="patient"><div class="topline"><h3>${a.patient}</h3>${badge(a)}</div><p>${a.service} · ${a.predicted_service_minutes} min predicted · ${a.provider}</p><div class="prediction"><span>Predicted service <b>${fmt(a.predicted_start)}</b></span><span>People ahead <b>${a.people_ahead??'—'}</b></span></div></div><div class="actions">${actions(a)}</div></article>`).join(''):'<div class="empty">No patients for this provider today.</div>'}
async function loadCalendar(){if(!config.today)return;const day=$('#calDate').value||config.today,p=$('#calProvider').value||config.providers[0];const slots=await request(`/api/availability?day=${day}&provider=${encodeURIComponent(p)}`);$('#slots').innerHTML=slots.map(s=>`<button class="slot ${s.status}" ${s.status==='booked'?'disabled':''} data-time="${s.time}"><b>${fmt(s.time)}</b><span>${s.status==='booked'?'Booked':'Available'}</span></button>`).join('');$$('.slot.available').forEach(b=>b.onclick=()=>{showTab('add');const f=$('#onlineForm');f.appointment_date.value=day;f.scheduled_time.value=b.dataset.time;f.provider.value=p;toast(`Selected ${fmt(b.dataset.time)} on ${day}`)})}
async function loadNotifications(){const n=await request('/api/notifications');$('#notificationList').innerHTML=n.length?n.map(x=>`<article class="note"><div><b>${x.event.replaceAll('_',' ').toUpperCase()}</b><span>${x.created_at.replace('T',' ')}</span></div><p>${x.message}</p><small>SMS: ${x.phone||'not provided'} · Email: ${x.email||'not provided'} · ${x.delivery}</small></article>`).join(''):'<div class="empty">No notifications yet.</div>'}
async function setStatus(id,s){try{await request(`/api/appointments/${id}/status/${s}`,{method:'POST'});toast(s==='no_show'?'No-show recorded. Queue recovered and next patient notified.':'Queue updated');await loadAll()}catch(e){toast(e.message,true)}}
async function checkIn(id){try{await request(`/api/appointments/${id}/check-in`,{method:'POST'});toast('Patient checked in');await loadAll()}catch(e){toast(e.message,true)}}
function showTab(id){$$('.tab').forEach(x=>x.classList.toggle('active',x.id===id));$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id))}
$$('.tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function formData(f,source){const d=Object.fromEntries(new FormData(f));return {...d,source,appointment_date:d.appointment_date||config.today,scheduled_time:d.scheduled_time||null,urgency:d.urgency||'normal'}}
async function submit(f,source){try{await request('/api/appointments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formData(f,source))});f.reset();$$('.providerSelect').forEach(x=>x.value=config.providers[0]);toast(source==='walk_in'?'Walk-in added to live queue':'Appointment booked and notification created');showTab('queue');await loadAll()}catch(e){toast(e.message,true)}}
$('#onlineForm').onsubmit=e=>{e.preventDefault();submit(e.target,'online')};$('#walkinForm').onsubmit=e=>{e.preventDefault();submit(e.target,'walk_in')};
async function init(){config=await request('/api/config');const providerOpts=config.providers.map(x=>`<option>${x}</option>`).join('');const serviceOpts=Object.entries(config.services).map(([x,m])=>`<option value="${x}">${x} · ~${m} min</option>`).join('');$$('.providerSelect').forEach(x=>x.innerHTML=providerOpts);$$('.serviceSelect').forEach(x=>x.innerHTML=serviceOpts);$('#queueProvider').innerHTML=providerOpts;$('#calProvider').innerHTML=providerOpts;$('#calDate').value=config.today;$('#onlineForm').appointment_date.value=config.today;$('#queueProvider').onchange=loadQueue;$('#calProvider').onchange=loadCalendar;$('#calDate').onchange=loadCalendar;await loadAll();try{const ws=new WebSocket('ws://localhost:8000/ws');ws.onmessage=()=>loadAll();setInterval(()=>ws.readyState===1&&ws.send('ping'),20000)}catch{}}
init();
